version: '2'
services:
  nginx:
    image: nginx
    # container: reverse_proxy
    # volumes:
      # - .:/usr/share/nginx/html
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./test:/test
    # network_mode: "host"
    ports:
    #   # - "5432:80"
      - "80:80"
    restart: always
    
    
